export default defineAppConfig({
  title: 'PT. Hajjah Tini Berkah Jaya',
  description: 'PT Hajjah Tini Berkah Jaya menyediakan solusi inovatif dalam pengelolaan limbah makanan kering dan produksi pakan ternak berkualitas tinggi. Kami berkomitmen untuk menciptakan keberlanjutan dan efisiensi bagi bisnis Anda. Pelajari lebih lanjut tentang layanan kami dan hubungi kami untuk konsultasi gratis.',
  email: 'kontak@hajjahtiniberkahjaya.com',
  phone: '0812 9040 7297',
  social: {
    twitter: 'https://twitter.com/hajjahtiniberkahjaya',
    facebook: 'https://www.facebook.com/hajjahtiniberkahjaya',
    linkedin: 'https://www.linkedin.com/company/hajjahtiniberkahjaya',
    instagram: 'https://www.instagram.com/hajjahtiniberkahjaya',
    youtube: 'https://www.youtube.com/channel/hajjahtiniberkahjaya',
  },
  links: [
    { label: 'Beranda', to: '/' },
    { label: 'Tentang Kami', to: '/' },
    { label: 'Layanan', to: '/' },
    { label: 'Produk', to: '/' },
    { label: 'Galeri', to: '/' },
    { label: 'Blog', to: '/' },
    { label: 'Kontak', to: '/' },
  ],
  hero: {
    headline: 'Ubah Limbah Makanan Jadi',
    typerHeadline: ['Pakan Ternak Berkualitas', 'Keuntungan Bisnis', 'Keseimbangan Lingkungan'],
    subHeadline: 'PT. Hajjah Tini Berkah Jaya hadir sebagai solusi cerdas untuk mengelola limbah makanan Anda. Dapatkan pakan ternak berkualitas dan kurangi dampak lingkungan.',
    ctaText: 'Konsultasikan Sekarang',
    videoPosterImageUrl: '/images/about13.jpg',
    videoUrl: '/media/movie.mp4',
  },
})
